server:
  port: 8899
logging:
  path: logs
  file: mylog.log
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: root
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
